---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cutomer
  labels:
    app: cutomer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cutomer
  template:
    metadata:
      labels:
        app: cutomer
    spec:
      containers:
        - name: cutomer
          image: username/cutomer:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: owner
  labels:
    app: owner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owner
  template:
    metadata:
      labels:
        app: owner
    spec:
      containers:
        - name: owner
          image: username/owner:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider
  labels:
    app: rider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rider
  template:
    metadata:
      labels:
        app: rider
    spec:
      containers:
        - name: rider
          image: username/rider:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: cutomer
  labels:
    app: cutomer
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: cutomer


---


apiVersion: v1
kind: Service
metadata:
  name: owner
  labels:
    app: owner
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: owner


---


apiVersion: v1
kind: Service
metadata:
  name: rider
  labels:
    app: rider
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: rider

